In [1]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49

In [2]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Invertir el vector

In [3]:
vector=np.flip(vector)
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### Crear una matriz 3x3 con valores de 0 a 8

In [4]:
matriz33 = np.arange(9)
matriz33.resize(3,3)
print(matriz33)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Encontrar los indices que no son ceros del arrays [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [5]:
vector2= np.array( [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0] , dtype='float' )
np.where(vector2 != 0)

(array([ 0,  1,  2,  3,  4,  6, 10, 11, 12, 13, 14], dtype=int64),)

### Crear una matriz identidad de 6x6

In [6]:
identidad = np.identity(6)
print(identidad)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Crear una matriz con valores al azar con forma 3x3x3 

In [7]:
a = np.random.random((3,3,3))*10
print(a)

[[[8.28731549 3.40821205 9.09028462]
  [8.06634776 1.01081729 2.28047946]
  [3.56027523 3.61207705 9.93868884]]

 [[9.53730307 2.03243726 7.46511075]
  [8.60406433 4.13632915 6.54125062]
  [8.9534394  4.32987663 1.43834082]]

 [[9.47086564 7.96718035 0.70023105]
  [8.29785416 3.03104037 4.88403845]
  [6.48453549 9.37965987 3.45532631]]]


### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [8]:
print (np.argmin(a))
print (np.argmax(a))

20
8


### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [16]:
y=np.ones((10,10))
y[1:9,1:9]=0
print(y)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [18]:
a=np.arange(5)
b=np.ones((5,1))
print(a*b)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### Crear dos arrays al azar A y B, verificar si son iguales

In [38]:
a = np.random.random(8)*10
b = np.random.random(8)*10
vedadero=a==b
vedadero.all()


False

In [33]:
# 