PEQUEÑO PAQUETE DE NORMALIZACIÓN

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
Min_Max = preprocessing.MinMaxScaler()
Ordinal =preprocessing.OrdinalEncoder()


def one_hot_cols(df,cols_to_one):
    one_hot=pd.get_dummies(df,cols_to_one,columns=cols_to_one)
    return one_hot


def fit_cols(df, cols_to_fit,fit_function ):
    for col in cols_to_fit:
        df[col] = pd.DataFrame(fit_function.fit_transform(pd.DataFrame(df[col])),columns=[col])
    return df


def split_Dataset(mypandas, cols_for_Y,size=0.2,state=1):
    
    X =  mypandas.drop(cols_for_Y, axis=1)
    Y = mypandas[cols_for_Y]
    X.head()
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=size, random_state=state)
    return X_train.to_numpy(), X_test.to_numpy(), Y_train.to_numpy(), Y_test.to_numpy()



Cargamos el dataset con pandas para normalizar datos y vemos lo que hay en el conjunto de datos

In [9]:
data_origin = pd.read_csv(r'datasets/Churn_Modelling.csv')
data_origin.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [10]:
data_origin.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [11]:
dataset = data_origin.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
dataset.head()


CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

La primera opcion es convertir Geography y Gender en one_hot


In [12]:
dataset1 = one_hot_cols(dataset,['Geography','Gender'])
dataset1.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1                 1   
1               1        112542.58       0                 0   
2               0        113931.57       1                 1   
3               0         93826.63       0                 1   
4               1         79084.10       0                 0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                  0                0              1            0  
1                  0                1              1            0  
2                  0                0              1            0  
3                  0                0              1            0  
4                  0                1              1            0

Otra opcion es convertir las columnas con label a ordinal

In [13]:
dataset2= fit_cols(dataset,['Gender','Geography'],Ordinal)
dataset2.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619        0.0     0.0   42       2       0.00              1   
1          608        2.0     0.0   41       1   83807.86              1   
2          502        0.0     0.0   42       8  159660.80              3   
3          699        0.0     0.0   39       1       0.00              2   
4          850        2.0     0.0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

Debemos escalar los valores entre 0 y 1

In [14]:
dataset3= fit_cols(dataset,dataset.columns,Min_Max)


dataset3.head(20)

CreditScore  Geography  Gender       Age  Tenure   Balance  NumOfProducts  \
0         0.538        0.0     0.0  0.324324     0.2  0.000000       0.000000   
1         0.516        1.0     0.0  0.310811     0.1  0.334031       0.000000   
2         0.304        0.0     0.0  0.324324     0.8  0.636357       0.666667   
3         0.698        0.0     0.0  0.283784     0.1  0.000000       0.333333   
4         1.000        1.0     0.0  0.337838     0.2  0.500246       0.000000   
5         0.590        1.0     1.0  0.351351     0.8  0.453394       0.333333   
6         0.944        0.0     1.0  0.432432     0.7  0.000000       0.333333   
7         0.052        0.5     0.0  0.148649     0.4  0.458540       1.000000   
8         0.302        0.0     1.0  0.351351     0.4  0.566170       0.333333   
9         0.668        0.0     1.0  0.121622     0.2  0.536488       0.000000   
10        0.356        0.0     1.0  0.175676     0.6  0.406606       0.333333   
11        0.294        1.0     1.0  0.081081     0.3  0.000000       0.333333   
12        0.252        0.0     0.0  0.216216     1.0  0.000000       0.333333   
13        0.398        0.0     0.0  0.094595     0.5  0.000000       0.333333   
14        0.570        1.0     0.0  0.229730     0.7  0.000000       0.333333   
15        0.532        0.5     1.0  0.364865     0.3  0.570468       0.333333   
16        0.606        0.5     1.0  0.540541     0.1  0.528513       0.000000   
17        0.398        1.0     0.0  0.081081     0.9  0.000000       0.333333   
18        0.474        1.0     1.0  0.364865     0.6  0.000000       0.000000   
19        0.752        0.0     0.0  0.081081     0.6  0.000000       0.333333   

    HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0         1.0             1.0         0.506735     1.0  
1         0.0             1.0         0.562709     0.0  
2         1.0             0.0         0.569654     1.0  
3         0.0             0.0         0.469120     0.0  
4         1.0             1.0         0.395400     0.0  
5         1.0             0.0         0.748797     1.0  
6         1.0             1.0         0.050261     0.0  
7         1.0             0.0         0.596733     1.0  
8         0.0             1.0         0.374680     0.0  
9         1.0             1.0         0.358605     0.0  
10        0.0             0.0         0.400886     0.0  
11        1.0             0.0         0.381929     0.0  
12        1.0             0.0         0.131260     0.0  
13        0.0             0.0         0.954322     0.0  
14        1.0             1.0         0.329732     0.0  
15        0.0             1.0         0.321609     0.0  
16        1.0             0.0         0.025433     1.0  
17        1.0             1.0         0.071981     0.0  
18        0.0             0.0         0.793442     0.0  
19        1.0             1.0         0.273588     0.0

In [15]:


X_train, X_test, Y_train, Y_test = split_Dataset(dataset,['Exited'])

In [16]:
print(X_train)


[[0.556      0.5        1.         ... 0.         1.         0.62374707]
 [0.552      0.         0.         ... 0.         0.         0.20548582]
 [0.524      0.5        0.         ... 1.         1.         0.22871499]
 ...
 [0.644      0.         0.         ... 1.         1.         0.46012449]
 [0.626      0.         0.         ... 1.         1.         0.50583491]
 [0.826      0.5        1.         ... 1.         0.         0.16727277]]
